lesson-3
MaryiaTS/if-html pull request #3
Opened 2022-10-15 22:06 UTC by MaryiaTS

Made new branch called 'lesson-3'. Added metatags  with content. Added an image. Added a list. Added a table. added a form considering all tasks.

2022-10-16 15:48 UTC, 5tronciy requested changes
There are a lot of unnecessary slashes. I haven't attended all of them, but you should check all tags and fix, if necessary.

2022-10-16 15:48 UTC, 5tronciy commented on index.html
> +    <img src="./image/blueflower.jpg" alt="blue flower" />
The image is absent.

2022-10-16 15:48 UTC, 5tronciy commented on index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
Trailing slash on void elements has no effect.

2022-10-16 15:48 UTC, 5tronciy commented on index.html
> +    <hr />
Trailing slash on void elements has no effect.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hr

2022-10-16 15:48 UTC, 5tronciy commented on index.html
> +    <img src="./image/blueflower.jpg" alt="blue flower" />
Trailing slash on void elements has no effect.

2022-10-16 15:48 UTC, 5tronciy commented on index.html
> +          <input id="level" type="range" name="level" min="0" max="10" />
Look carefully at the task.

2022-10-16 15:48 UTC, 5tronciy commented on index.html
> +          </select>
'What does http stand for' is missed.

2022-10-16 15:49 UTC, 5tronciy commented
And don't forget requesting review after the task is ready.

2022-10-17 14:58 UTC, MaryiaTS commented
> There are a lot of unnecessary slashes. I haven't attended all of them, but you should check all tags and fix, if necessary.

Эти слэши ставятся в непарных тегах при использовании prettier, но в этом проекте я вручную их уберу

2022-10-24 19:49 UTC, 5tronciy commented
> > There are a lot of unnecessary slashes. I haven't attended all of them, but you should check all tags and fix, if necessary.
> 
> Эти слэши ставятся в непарных тегах при использовании prettier, но в этом проекте я вручную их уберу

Yep, Prettier do that :D
Anyway, it is not a mistake, and the code will work the same. Just attend you that the trailing slash doesn't influence a document.
[Here](https://github.com/validator/validator/wiki/Markup-%C2%BB-Void-elements#trailing-slashes-in-void-element-start-tags-do-not-mark-the-start-tags-as-self-closing) you may read more about it.

2022-10-24 20:13 UTC, 5tronciy approved these changes
Good work!
Approve.

2022-10-24 20:14 UTC, merged